sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: _
    bucket-name: _
    access-key-id: _
    access-key-secret: _
  redis:
    database: 0
    host: localhost
    port: 6379
